disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - vertical_whitespace
  - cyclomatic_complexity
opt_in_rules: # some rules are only opt-in

included: # paths to include during linting. `--path` is ignored if present.
  - gourmetsearch/Sources
excluded: # paths to ignore during linting. Takes precedence over `included`.
