//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 3 files.
  struct file {
    /// Resource file `GoogleService-Info-Debug.plist`.
    static let googleServiceInfoDebugPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info-Debug", pathExtension: "plist")
    /// Resource file `GoogleService-Info-Release.plist`.
    static let googleServiceInfoReleasePlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info-Release", pathExtension: "plist")
    /// Resource file `Settings.bundle`.
    static let settingsBundle = Rswift.FileResource(bundle: R.hostingBundle, name: "Settings", pathExtension: "bundle")
    
    /// `bundle.url(forResource: "GoogleService-Info-Debug", withExtension: "plist")`
    static func googleServiceInfoDebugPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoDebugPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "GoogleService-Info-Release", withExtension: "plist")`
    static func googleServiceInfoReleasePlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoReleasePlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Settings", withExtension: "bundle")`
    static func settingsBundle(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.settingsBundle
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 6 images.
  struct image {
    /// Image `breakfast`.
    static let breakfast = Rswift.ImageResource(bundle: R.hostingBundle, name: "breakfast")
    /// Image `chukagai1`.
    static let chukagai1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "chukagai1")
    /// Image `chukagai2`.
    static let chukagai2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "chukagai2")
    /// Image `chukagai3`.
    static let chukagai3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "chukagai3")
    /// Image `smoothie`.
    static let smoothie = Rswift.ImageResource(bundle: R.hostingBundle, name: "smoothie")
    /// Image `sushi`.
    static let sushi = Rswift.ImageResource(bundle: R.hostingBundle, name: "sushi")
    
    /// `UIImage(named: "breakfast", bundle: ..., traitCollection: ...)`
    static func breakfast(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.breakfast, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "chukagai1", bundle: ..., traitCollection: ...)`
    static func chukagai1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.chukagai1, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "chukagai2", bundle: ..., traitCollection: ...)`
    static func chukagai2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.chukagai2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "chukagai3", bundle: ..., traitCollection: ...)`
    static func chukagai3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.chukagai3, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "smoothie", bundle: ..., traitCollection: ...)`
    static func smoothie(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.smoothie, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "sushi", bundle: ..., traitCollection: ...)`
    static func sushi(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sushi, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
